// Program where the user has to guess a number generated by a program
const prompt = require("prompt-sync")();

function guessNumber() {
  // random int from 1 to 10
  const random = Math.floor(Math.random() * 10) + 1;

  let num = parseInt(prompt("Guess a number from 1 to 10: "));

  while (num !== random) {
    num = parseInt(prompt("Guess a number from 1 to 10: "));
  }

  if (num === random) {
    console.log("You guessed the correct number.");
  }
}

guessNumber();
